### ISSUE TITLE
keeps closing?

### ISSUE THREAD

**Issue by JimmyNeutronsBitch** [modded-ubuntu/modded-ubuntu#124]
Ubuntu just randomly stops working
![Screenshot_20230924_194405_Termux](https://github.com/modded-ubuntu/modded-ubuntu/assets/107628315/4d188cfc-212c-4616-8862-6ae9ecb73782)

**Comment by BDhackers009** [comment]
This is because youre using android 12 or higher. This is called Phantom Proccess. Please reffer to this article to fix your issue.
[Disable Phantom Proccess Killing](https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr)
