### ISSUE TITLE
VS code not running please help me sir

### ISSUE THREAD

**Issue by Ravan123456789** [modded-ubuntu/modded-ubuntu#13]
VS code installed but not running please sir help me

**Comment by BDhackers009** [comment]
what is the architecture of your device?

if you don't know how to check it..type following command:-

dpkg --print-architecture

if the output is aarch64 or arm64 then  type 

code --verbose

and send us the ouput. 

if the output of "dpkg --print-architecture" is  or armhf then  please consider to use any other ide or editor... because i cant find the armhf🙂

**Comment by anandhkumar-dev** [comment]
i have same problem this is my output 
7124:0730/101744.976938:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/code/chrome-sandbox is owned by root and has mode 4755

**Comment by BDhackers009** [comment]
🐧 open terminal and type:

code --no-sandbox

**Comment by ShivaShirsath** [comment]
```
code --no-sandbox # used it by loged in user (not root)
```
