### ISSUE TITLE
chromium nor Firefox working?

### ISSUE THREAD

**Issue by JimmyNeutronsBitch** [modded-ubuntu/modded-ubuntu#98]
I've tried to open, remove and re-download, chromium and it still wouldn't open
so then I tried the same for Firefox and I get same results

**Comment by BDhackers009** [comment]
Choose browser when running gui.sh and it will install browser for you

**Comment by JimmyNeutronsBitch** [comment]
> Choose browser when running gui.sh and it will install browser for you

I done that already, but it won't open

**Comment by JimmyNeutronsBitch** [comment]
mushy@localhost:~$ chromium
/usr/lib/chromium/chromium: error while loading shared libraries: libx264.so.163: cannot enable executable stack as shared object requires: Permission denied

**Comment by BDhackers009** [comment]
> mushy@localhost:~$ chromium /usr/lib/chromium/chromium: error while loading shared libraries: libx264.so.163: cannot enable executable stack as shared object requires: Permission denied

try running firefox

**Comment by JimmyNeutronsBitch** [comment]
mushy@localhost:~$ firefox

Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox

mushy@localhost:~$ snap install firefox
error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory

**Comment by BDhackers009** [comment]
> mushy@localhost:~$ firefox
> 
> Command '/usr/bin/firefox' requires the firefox snap to be installed. Please install it with:
> 
> snap install firefox
> 
> mushy@localhost:~$ snap install firefox error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory

follow this [Fix](https://github.com/modded-ubuntu/modded-ubuntu/issues/98#issuecomment-1474337882)

**Comment by JimmyNeutronsBitch** [comment]
E: Packages were downgraded and -y was used without --allow-downgrades.

**Comment by mxnarilaishi** [comment]
> > mushy@localhost:~$ firefox
> > Command '/usr/bin/firefox' requires the firefox snap to be installed. Please install it with:
> > snap install firefox
> > mushy@localhost:~$ snap install firefox error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory
> 
> follow this [Fix](https://github.com/modded-ubuntu/modded-ubuntu/issues/98#issuecomment-1474337882)

didn't fix anything, just got more errors :

econ@localhost:~$ curl https://raw.githubusercontent.com/modded-ubuntu/modded-ubuntu/master/distro/firefox.sh | sudo bash
  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed
100  10414 100  10414   0      0 100.6k      0                              0
error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory
deb https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy main
Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";
Ign:1 http://ftp.debian.org/debian buster InRelease
Ign:2 http://ftp.debian.org/debian buster-updates InRelease
Err:3 http://ftp.debian.org/debian buster Release
  404  Not Found [IP: 151.101.130.132 80]
Err:4 http://ftp.debian.org/debian buster-updates Release
  404  Not Found [IP: 151.101.130.132 80]
Hit:5 https://packages.microsoft.com/repos/code stable InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports resolute InRelease
Get:7 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease [24.6 kB]
Err:7 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease
  The following signatures were invalid: 0AB215679C571D1C8325275B9BDB3D89CE49EC21 (untrusted public key algorithm: rsa1024) The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AEBDF4819BE21867
Hit:8 http://ports.ubuntu.com/ubuntu-ports resolute-updates InRelease
Hit:9 http://ports.ubuntu.com/ubuntu-ports resolute-backports InRelease
Hit:10 http://ports.ubuntu.com/ubuntu-ports resolute-security InRelease
Reading package lists... Done
E: The repository 'http://ftp.debian.org/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ftp.debian.org/debian buster-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: OpenPGP signature verification failed: https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease: The following signatures were invalid: 0AB215679C571D1C8325275B9BDB3D89CE49EC21 (untrusted public key algorithm: rsa1024) The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AEBDF4819BE21867
E: The repository 'https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list:1 and /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.sources:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list:1 and /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.sources:1
N: Missing Signed-By in the sources.list(5) entry for 'http://ftp.debian.org/debian'
N: Missing Signed-By in the sources.list(5) entry for 'http://ftp.debian.org/debian'
N: Missing Signed-By in the sources.list(5) entry for 'https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu'
firefox is already the newest version (1:1snap1-0ubuntu8).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 0
Warning: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list:1 and /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.sources:1
Warning: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list:1 and /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.sources:1

**Comment by BDhackers009** [comment]
We fixed these issues in the next incoming update its already under testing. Please wait a few days we are working on a major update.
